name: Android CI Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug version
        run: ./gradlew assembleDebug

      - name: upload-artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: build-${{ github.sha }}-${{ github.ref_name }}-${{ github.run_number }}
          path: app/build/outputs/**/*.apk
