name: Release to Amazon Appstore

on:
  

jobs:
  build-and-upload:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '34'
          build-tools: '34.0.0'
      - run: sdkmanager tools platform-tools
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/settings.gradle', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - name: Decrypt keystore file
#        env:
#          BASE64_KEYSTORE: ${{ secrets.RELEASE_STORE_FILE }}
#        run: |
#          echo "$BASE64_KEYSTORE" | base64 --decode > keystore.jks
#          ls -l keystore.jks

      - name: Get Tag
        id: var
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build Release Apk
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.BASE64KEY }}
         alias: ${{ secrets.ALIAS }}
         keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
         keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed APP APK
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
         mention-authors: false
         mention-new-contributors: true
         include-compare: true
         semver: false

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.var.outputs.tag }}
          name: TodoTracker ${{ steps.var.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          files: ${{ steps.sign_apk.outputs.signedReleaseFile }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

#      - name: Upload APK
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
#          asset_name: TodoTracker-${{ steps.var.outputs.tag }}.apk
#          asset_content_type: application/zip


#      - name: Upload to Amazon Appstore
#        uses: galonga/upload-amazon-appstore@v1.0.5
#        with:
#          client_id: ${{ secrets.AMAZON_APPSTORE_CLIENT_ID }}
#          client_secret: ${{ secrets.AMAZON_APPSTORE_CLIENT_SECRET }}
#          refresh_token: ${{ secrets.AMAZON_APPSTORE_REFRESH_TOKEN }}
#          package_name: 'com.mostafadevo.todotrackercompose'
#          file_path: 'app/build/outputs/apk/release/app-release.apk'
